/**
 * PowerShell Generator
 * Generates PowerShell scripts for downloading content
 */

import type { LogEntry } from '@/types';
import { escapePowerShellArg } from '../escapers/powershell-escaper';

/**
 * Generate PowerShell script
 *
 * @param entries - Log entries to export
 * @returns PowerShell script with Invoke-WebRequest commands
 */
export function generatePowerShell(entries: LogEntry[]): string {
  const lines: string[] = [
    '# Generated by WebreqSniffer',
    '$ProgressPreference = "SilentlyContinue"',
    '',
  ];

  for (let i = 0; i < entries.length; i++) {
    const entry = entries[i];
    if (!entry) continue;

    const url = `"${escapePowerShellArg(entry.url)}"`;

    lines.push(`# Request ${i + 1}`);

    if (entry.headers && Object.keys(entry.headers).length > 0) {
      lines.push('$headers = @{');
      for (const [key, value] of Object.entries(entry.headers)) {
        const escapedValue = escapePowerShellArg(value);
        lines.push(`    "${key}" = "${escapedValue}"`);
      }
      lines.push('}');
      lines.push(`Invoke-WebRequest -Uri ${url} -Headers $headers`);
    } else {
      lines.push(`Invoke-WebRequest -Uri ${url}`);
    }

    lines.push('');
  }

  return lines.join('\n');
}
