/**
 * Unit Tests for Export Logic
 */

import { describe, it, expect } from 'vitest';
import {
  escapeShellArg,
  escapePowerShellArg,
  generateUrlList,
  generateBashCurl,
  generateBashCurlHeaders,
  generateBashYtDlp,
  generatePowerShell,
  generateFilename,
  generateExportContent,
} from '@/background/export';
import type { LogEntry, ExportFormat } from '@/types';

describe('Export Logic', () => {
  const mockEntries: LogEntry[] = [
    {
      id: '1',
      requestId: 'req1',
      url: 'https://example.com/video.m3u8',
      method: 'GET',
      type: 'media',
      tabId: 1,
      frameId: 0,
      timestamp: Date.now(),
      dedupeKey: 'key1',
      headers: {
        'User-Agent': 'Mozilla/5.0',
        Referer: 'https://example.com',
      },
    },
    {
      id: '2',
      requestId: 'req2',
      url: 'https://cdn.example.com/segment.ts',
      method: 'GET',
      type: 'media',
      tabId: 1,
      frameId: 0,
      timestamp: Date.now(),
      dedupeKey: 'key2',
    },
  ];

  describe('escapeShellArg', () => {
    it('should escape single quotes in Bash', () => {
      expect(escapeShellArg("it's a test")).toBe("'it'\\''s a test'");
    });

    it('should wrap argument in single quotes', () => {
      expect(escapeShellArg('simple')).toBe("'simple'");
    });

    it('should handle special characters', () => {
      expect(escapeShellArg('test$variable')).toBe("'test$variable'");
      expect(escapeShellArg('test`command`')).toBe("'test`command`'");
    });
  });

  describe('escapePowerShellArg', () => {
    it('should escape backticks', () => {
      expect(escapePowerShellArg('test`quote')).toBe('test``quote');
    });

    it('should escape dollar signs', () => {
      expect(escapePowerShellArg('test$variable')).toBe('test`$variable');
    });

    it('should escape double quotes', () => {
      expect(escapePowerShellArg('test"quote')).toBe('test`"quote');
    });

    it('should escape newlines and carriage returns', () => {
      expect(escapePowerShellArg('test\nline')).toBe('test`nline');
      expect(escapePowerShellArg('test\rreturn')).toBe('test`rreturn');
    });
  });

  describe('generateUrlList', () => {
    it('should generate plain URL list', () => {
      const result = generateUrlList(mockEntries);
      expect(result).toContain('https://example.com/video.m3u8');
      expect(result).toContain('https://cdn.example.com/segment.ts');
      expect(result.endsWith('\n')).toBe(true);
    });

    it('should separate URLs with newlines', () => {
      const result = generateUrlList(mockEntries);
      const lines = result.trim().split('\n');
      expect(lines).toHaveLength(2);
    });
  });

  describe('generateBashCurl', () => {
    it('should generate Bash curl script', () => {
      const result = generateBashCurl(mockEntries);
      expect(result).toContain('#!/bin/bash');
      expect(result).toContain('# Generated by WebreqSniffer');
      expect(result).toContain("curl -L 'https://example.com/video.m3u8'");
      expect(result).toContain("curl -L 'https://cdn.example.com/segment.ts'");
    });

    it('should escape URLs properly', () => {
      const entries: LogEntry[] = [
        {
          ...mockEntries[0],
          url: "https://example.com/test's",
        },
      ];
      const result = generateBashCurl(entries);
      expect(result).toContain("curl -L 'https://example.com/test'\\''s'");
    });
  });

  describe('generateBashCurlHeaders', () => {
    it('should generate Bash curl with headers', () => {
      const result = generateBashCurlHeaders(mockEntries);
      expect(result).toContain('#!/bin/bash');
      expect(result).toContain('-H');
      expect(result).toContain('User-Agent: Mozilla/5.0');
      expect(result).toContain('Referer: https://example.com');
    });

    it('should handle entries without headers', () => {
      const result = generateBashCurlHeaders(mockEntries);
      expect(result).toContain("curl -L 'https://cdn.example.com/segment.ts'");
    });
  });

  describe('generateBashYtDlp', () => {
    it('should generate Bash yt-dlp script', () => {
      const result = generateBashYtDlp(mockEntries);
      expect(result).toContain('#!/bin/bash');
      expect(result).toContain('yt-dlp');
      expect(result).toContain('--add-header');
      expect(result).toContain('User-Agent: Mozilla/5.0');
    });

    it('should add referer flag when present', () => {
      const result = generateBashYtDlp(mockEntries);
      expect(result).toContain('--referer');
      expect(result).toContain("'https://example.com'");
    });

    it('should handle entries without headers', () => {
      const result = generateBashYtDlp([mockEntries[1]]);
      expect(result).toContain('yt-dlp');
      expect(result).toContain("'https://cdn.example.com/segment.ts'");
    });
  });

  describe('generatePowerShell', () => {
    it('should generate PowerShell script', () => {
      const result = generatePowerShell(mockEntries);
      expect(result).toContain('# Generated by WebreqSniffer');
      expect(result).toContain('$ProgressPreference = "SilentlyContinue"');
      expect(result).toContain('Invoke-WebRequest');
    });

    it('should include headers when present', () => {
      const result = generatePowerShell(mockEntries);
      expect(result).toContain('$headers = @{');
      expect(result).toContain('"User-Agent"');
      expect(result).toContain('"Mozilla/5.0"');
    });

    it('should escape special characters for PowerShell', () => {
      const entries: LogEntry[] = [
        {
          ...mockEntries[0],
          url: 'https://example.com/test$var',
        },
      ];
      const result = generatePowerShell(entries);
      expect(result).toContain('test`$var');
    });
  });

  describe('generateFilename', () => {
    it('should replace {date} placeholder', () => {
      const filename = generateFilename('log_{date}.txt', 'url-list', mockEntries);
      expect(filename).toMatch(/log_\d{4}-\d{2}-\d{2}\.txt/);
    });

    it('should replace {domain} placeholder', () => {
      const filename = generateFilename('log_{domain}.txt', 'url-list', mockEntries);
      expect(filename).toBe('log_example.com.txt');
    });

    it('should replace {ext} placeholder based on format', () => {
      expect(generateFilename('log.{ext}', 'url-list', mockEntries)).toBe('log.txt');
      expect(generateFilename('log.{ext}', 'bash-curl', mockEntries)).toBe('log.sh');
      expect(generateFilename('log.{ext}', 'powershell', mockEntries)).toBe('log.ps1');
    });

    it('should handle all placeholders together', () => {
      const filename = generateFilename('netlog_{date}_{domain}.{ext}', 'bash-curl', mockEntries);
      expect(filename).toMatch(/netlog_\d{4}-\d{2}-\d{2}_example\.com\.sh/);
    });

    it('should sanitize domain names', () => {
      const entries: LogEntry[] = [
        {
          ...mockEntries[0],
          url: 'https://sub-domain.example.com/test',
        },
      ];
      const filename = generateFilename('log_{domain}.txt', 'url-list', entries);
      expect(filename).toBe('log_sub-domain.example.com.txt');
    });
  });

  describe('generateExportContent', () => {
    it('should generate URL list format', () => {
      const content = generateExportContent(mockEntries, 'url-list');
      expect(content).toContain('https://example.com/video.m3u8');
    });

    it('should generate Bash curl format', () => {
      const content = generateExportContent(mockEntries, 'bash-curl');
      expect(content).toContain('#!/bin/bash');
      expect(content).toContain('curl -L');
    });

    it('should generate Bash curl with headers format', () => {
      const content = generateExportContent(mockEntries, 'bash-curl-headers');
      expect(content).toContain('-H');
    });

    it('should generate Bash yt-dlp format', () => {
      const content = generateExportContent(mockEntries, 'bash-yt-dlp');
      expect(content).toContain('yt-dlp');
    });

    it('should generate PowerShell format', () => {
      const content = generateExportContent(mockEntries, 'powershell');
      expect(content).toContain('Invoke-WebRequest');
    });

    it('should throw error for unknown format', () => {
      expect(() => generateExportContent(mockEntries, 'unknown' as ExportFormat)).toThrow(
        'Unknown export format'
      );
    });
  });
});
